name: Publish
on:
  push:
    tags:
       - '*'
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: yarn
      - name: Run test
        run: yarn test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '12.x'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
